train_dir   : '/home/quc007/Research/qtrkx-gnn-tracking/data/train'
valid_dir   : '/home/quc007/Research/qtrkx-gnn-tracking/data/valid'
dataset     : 'mu200_1pT'
log_dir     : 'logs/test/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 4
n_valid     : 2
n_train     : 2
batch_size  : 1 
lr_c        : 0.01
n_iters     : 3
n_epoch     : 2
TEST_every  : 2
hid_dim     : 8
network     : 'QGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 18
log_verbosity: 2
EN_qc:
  PQC_id  : '10'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_all'
  n_layers : 1
  repetitions: 0
  n_qubits: 8
NN_qc:
  PQC_id  : '10'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_all'
  n_layers : 1
  repetitions: 0
  n_qubits: 8
