train_dir   : '/home/quc007/Research/qtrkx-gnn-tracking/data/train'
valid_dir   : '/home/quc007/Research/qtrkx-gnn-tracking/data/valid'
dataset     : 'mu200_1pT'
log_dir     : 'logs/test_QGNN_TNN_3/'
run_type    : 'new_run'
gpu         : '0'
n_files     : 100
n_valid     : 50
n_train     : 50
batch_size  : 1 
lr_c        : 0.01
n_iters     : 3
n_epoch     : 20
TEST_every  : 50
hid_dim     : 8
network     : 'QGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 18
log_verbosity: 2
EN_qc:
  PQC_id  : 'TNN_con3'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_TNN'
  n_layers : 1
  repetitions: 0
  n_qubits: 8
NN_qc:
  PQC_id  : 'TNN_con3'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_TNN'
  n_layers : 1
  repetitions: 0
  n_qubits: 8
