train_dir   : 'data/train'
valid_dir   : 'data/valid'
dataset     : 'mu200_1pT'
log_dir     : 'logs/test_qiskit_noise_con3/'
run_type    : 'new_run'
gpu         : '-1'
n_files     : 100
n_valid     : 50
n_train     : 50
batch_size  : 1 
lr_c        : 0.01
n_iters     : 3
n_epoch     : 20
TEST_every  : 50
hid_dim     : 8
network     : 'QGNN'
optimizer: 'Adam'
loss_func: 'BCELoss'
n_thread    : 12
log_verbosity: 2
EN_qc:
  PQC_id  : 'TNN_con3_qiskit'
  IEC_id  : 'simple_encoding_y_qiskit'
  MC_id   : 'measure_TNN_qiskit'
  dp_noise : 0.1
  n_layers : 1
  repetitions: 0
  n_qubits: 8
NN_qc:
  PQC_id  : 'TNN_con3_qiskit'
  IEC_id  : 'simple_encoding_y_qiskit'
  MC_id   : 'measure_TNN_qiskit'
  dp_noise : 0.1
  n_layers : 1
  repetitions: 0
  n_qubits: 8